### PR TITLE
4.0.4 screen shaking

### PR DESCRIPTION
**Pull request by da-tang**
Remove box-shadow on android-4
screen shaking on 4.0.4.
Not sure if it happens on android 3 or not.
Couldn’t find a QA phone with android 3.

### CODE REVIEW

**Comment by robinsharma** [comment]
@da-tang you need to make the changes in the `src` directory

**Comment by da-tang** [comment]
@robinsharma thanks.. searched through the project and got the wrong folder..
so how about dist? it will be auto-generated based on the ```src```?

**Comment by robinsharma** [comment]
@da-tang yup!

**Comment by lunaleaps** [comment]
@robinsharma is this good in?

**Comment by robinsharma** [comment]
@lunaleaps this definitely solves the problem but would remove the app-content box-shadow for all 4.x devices.
@jairajs89 what do you think?

**Comment by jairajs89** [comment]
That's how I fixed it before! You can remove the drop shadow, but then add it only during page transitions. Then you get it to look nice without shaking as well

Can we do it like that instead?

**Comment by lunaleaps** [comment]
@robinsharma @jairajs89 is this right?

**Comment by jairajs89** [comment]
@robinsharma @lunaleaps http://cdn.kik.com.s3.amazonaws.com/app/3.0.10/app.min.js

**Pull request merged**
